# ===========================
# nginx.conf para Load Balancer
# ===========================
events {
    worker_connections 1024;
}

http {

    upstream profesores_cluster {
        server 10.1.1.10:80 max_fails=3 fail_timeout=10s;
        server 10.1.1.11:80 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;

        root /var/www/public;
        index index.html;

        location /static/ {
            alias /var/www/public/;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /profesores/ {
            proxy_pass http://profesores_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Dashboard básico de estado de Nginx
        location /nginx_status {
            stub_status;
            allow all;
            #allow 192.168.1.133;
            #deny all;
        }
    }
}
